POST http://127.0.0.1:5001/account/register
Content-Type: application/json

{
  "email": "user2",
  "password": "123"
}

###
POST http://127.0.0.1:5001/account/login
Content-Type: application/json

{
  "email": "user2",
  "password": "123"
}

###
