POST http://127.0.0.1:5000/auth/register
Content-Type: application/json
Cookie: null;

{
  "username": "user1",
  "password": "pas"
}

###
GET http://127.0.0.1:5000/account/register
Accept: application/json

###
